# .github/workflows/pr.yml
name: pr
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4
      - run: rye pin 3.12         # pin your Python version
      - run: |                    # update the virtualenv and check
          rye sync             
          if [[ $(git diff --stat requirements.lock) != '' ]]; then
            echo 'requirements.lock not up-to-date'
            git diff requirements.lock
            exit 1
          fi
      - run: rye fmt --check      # check formatting is correct
      - run: rye lint             # and linting
      - run: rye run check        # typecheck too
      - run: rye run test_fast    # then run your tests!
      - run: rye run test_slow    # then run your tests!
